# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ReciteWords' do
  
  pod 'AFNetworking'
  pod 'SJDBMap'
  pod 'SJBorderLineView'
  pod 'Masonry'  
  pod 'SVProgressHUD'
end
